name: imageguard-scan
description: A GitHub Action to scan container images for vulnerabilities and generate a ImageVulnerability Resource in cluster.

inputs:
  name:
    description: 'Name of the person to greet'
    required: true
    # type: string
      # deploy_target:
      #   required: true
      #   type: string
      # perform_deploy:
      #   required: true
      #   type: boolean

runs:
  using: "composite"
  steps:
    - name: Deploy build to target
      # run: echo "Deploying build:${{ inputs.build_id }} to target:${{ inputs.deploy_target }}"
      shell: bash
      run: | 
        echo hello ${{ input.name }}