name: imageguard-scan
description: A GitHub Action to scan container images for vulnerabilities and generate a ImageVulnerability Resource in cluster.

inputs:
  name:
    description: 'Name of the person to greet!'
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy build to target
      shell: bash
      run: | 
        echo hello ${{ inputs.name }}