apiVersion: imageguard.k8s.io/v1
kind: ImageVulnerability
metadata:
  name: nginx-latest-vulnerability
spec:
  image: nginx:latest
  summary:
    critical: 2
    high: 55
    medium: 118
    low: 128
