name: imageguard-scan testing composite action
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run the imageguard-scan action
      uses: Shravankamble/imageguard-scan@v1
      with:
        image: nginx:latest
        path: imageguard-scan-resources/
    
    - name: trivy version
      run: | 
        trivy --version